#=========================================================#
#                     CustomPlugin                        #
#=========================================================#
Switcher:
   Permission: "egg.use"
   Cooldown-Enabled: true
   Cooldown: 10  #IN SECONDS
   Cooldown-Message: "&eYou still New &6Egg &ecooldown for another %time%s"
   Range-of-Blocks: 10
   No-Range-Message: "&cYou failed to swamp places whit %damagedplayer% as they`re out of range"
   Shooter-Message: "&eYou`ve swapped places whit &6%damagedplayer%"
   DamagedPlayer-Message: "&6%shooter% &ehas swapped places whit you"
Effect-Snowball:
   Permission: "Snowball.use"
   Cooldown-Enabled: true
   Cooldown: 20 #IN SECONDS
   Cooldown-Message: "&eYou still have &6Snowball &ecooldown for another %time%s." 
   Shooter-Message: "&eYou has been damaged &6%damagedplayer% &ewhit a &6Snownball"
   DamagedPlayer-Message: "&eYou were damaged by &6%shooter% &ewith a &6Snowball"
# > ALL TIMES BELLOW ARE IN TICKS, 1 SECOND = 20 TICKS. 
# > SO IF YOU WANT TO DO 15 SECONDS: 15 x 20 = 300.
# > <EFFECT>:<DURATION>:<AMPLIFIER>
   Effects:
   - SLOW:80:0
   - BLINDNESS:100:0
   - SLOW_DIGGING:80:1
